export const ENGINE_LIST_SOIL_TOOLS  = [
  {
    modelName: '',
    brandName: '',
    description: '',
    ref: '',
    conception: '',
    engineKwPower: null,
    engineCcPower: null,
    maxKmhSpeed: null,
    petrolLitreTank: null,
    tankLitre: null,
    weightKg: null,
    workingWidth: null,
    copiesNumber: 2,
    typeId: 10,
    imageUrl: ''
  },
  {
    modelName: '',
    brandName: '',
    description: '',
    ref: '',
    conception: '',
    engineKwPower: null,
    engineCcPower: null,
    maxKmhSpeed: null,
    petrolLitreTank: null,
    tankLitre: null,
    weightKg: null,
    workingWidth: null,
    copiesNumber: 2,
    typeId: 10,
    imageUrl: ''
  },
];
