export const ENGINE_LIST_HARVEST_EQUIPMENT  = [
  {
    modelName: 'Axial-flow 4000',
    brandName: 'Case IH',
    description: 'Pour moissoneuse-batteuse',
    ref: 'moissoneuse',
    conception: 'Cylindre Axial',
    engineKwPower: 210,
    engineCcPower: 180,
    maxKmhSpeed: 30,
    petrolLitreTank: 500,
    tankLitre: 600,
    autonomyMn: null,
    liftingHeightMeter: null,
    weightKg: 6000,
    workingWidth: 14,
    copiesNumber: 2,
    typeId: 10,
    imageUrl: 'https://nestjsfileuploadfarmingmachine.s3.eu-west-3.amazonaws.com/New-Holland.png'
  },
  {
    modelName: 'Lexion 8900',
    brandName: 'Claas',
    description: 'Pour moissoneuse-batteuse',
    ref: 'moissoneuse',
    conception: 'Hybride',
    engineKwPower: 485,
    engineCcPower: 460,
    maxKmhSpeed: 40,
    petrolLitreTank: 1150,
    tankLitre: 18000,
    autonomyMn: null,
    liftingHeightMeter: null,
    weightKg: 18700,
    workingWidth: 13.8,
    copiesNumber: 1,
    typeId: 10,
    imageUrl: 'https://nestjsfileuploadfarmingmachine.s3.eu-west-3.amazonaws.com/Massey-Ferguson.png',
  },
  {
    modelName: 'S790',
    brandName: 'John Deere',
    description: 'Pour moissoneuse-batteuse',
    ref: 'moissoneuse',
    conception: 'Conventionnelle',
    engineKwPower: 460,
    engineCcPower: 435,
    maxKmhSpeed: 40,
    petrolLitreTank: 1250,
    tankLitre: 14100,
    autonomyMn: null,
    liftingHeightMeter: null,
    weightKg: 19000,
    workingWidth: 12.2,
    copiesNumber: 2,
    typeId: 10,
    imageUrl: 'https://nestjsfileuploadfarmingmachine.s3.eu-west-3.amazonaws.com/Ks-Agrotech.png',
  },
  {
    modelName: 'Ideal 9T',
    brandName: 'Fendt',
    description: 'Pour moissoneuse-batteuse',
    ref: 'moissoneuse',
    conception: 'Rotor Unique',
    engineKwPower: 483,
    engineCcPower: 455,
    maxKmhSpeed: 40,
    petrolLitreTank: 1500,
    tankLitre: 17100,
    autonomyMn: null,
    liftingHeightMeter: null,
    weightKg: 21000,
    workingWidth: 12.2,
    copiesNumber: 1,
    typeId: 10,
    imageUrl: 'https://nestjsfileuploadfarmingmachine.s3.eu-west-3.amazonaws.com/John-Deere.png'
  },
  {
    modelName: 'CR10.90',
    brandName: 'New Holland',
    description: 'Pour moissoneuse-batteuse',
    ref: 'moissoneuse',
    conception: 'Twin Rotor',
    engineKwPower: 515,
    engineCcPower: 490,
    maxKmhSpeed: 30,
    petrolLitreTank: 1300,
    tankLitre: 14500,
    autonomyMn: null,
    liftingHeightMeter: null,
    weightKg: 24500,
    workingWidth: 13.7,
    copiesNumber: 1,
    typeId: 10,
    imageUrl: 'https://nestjsfileuploadfarmingmachine.s3.eu-west-3.amazonaws.com/John-Deere-2.png',
  },
  {
    modelName: 'Trion 750',
    brandName: 'Claas',
    description: 'Pour moissoneuse-batteuse',
    ref: 'moissoneuse',
    conception: 'Hybride',
    engineKwPower: 320,
    engineCcPower: 300,
    maxKmhSpeed: 30,
    petrolLitreTank: 800,
    tankLitre: 12000,
    autonomyMn: null,
    liftingHeightMeter: null,
    weightKg: 15000,
    workingWidth: 9.3,
    copiesNumber: 3,
    typeId: 10,
    imageUrl: 'https://nestjsfileuploadfarmingmachine.s3.eu-west-3.amazonaws.com/New-Holland.png'
  },
  {
    modelName: 'Tucano 580',
    brandName: 'Claas',
    description: 'Pour moissoneuse-batteuse',
    ref: 'moissoneuse',
    conception: 'Conventionnelle',
    engineKwPower: 280,
    engineCcPower: 260,
    maxKmhSpeed: 25,
    petrolLitreTank: 650,
    tankLitre: 10000,
    autonomyMn: null,
    liftingHeightMeter: null,
    weightKg: 13500,
    workingWidth: 7.7,
    copiesNumber: 2,
    typeId: 10,
    imageUrl: 'https://nestjsfileuploadfarmingmachine.s3.eu-west-3.amazonaws.com/Massey-Ferguson.png',
  },
  {
    modelName: 'TC5.90',
    brandName: 'New Holland',
    description: 'Pour moissoneuse-batteuse',
    ref: 'moissoneuse',
    conception: 'Conventionnelle',
    engineKwPower: 220,
    engineCcPower: 200,
    maxKmhSpeed: 30,
    petrolLitreTank: 400,
    tankLitre: 6400,
    autonomyMn: null,
    liftingHeightMeter: null,
    weightKg: 10500,
    workingWidth: 6.1,
    copiesNumber: 4,
    typeId: 10,
    imageUrl: 'https://nestjsfileuploadfarmingmachine.s3.eu-west-3.amazonaws.com/Ks-Agrotech.png',
  },
  {
    modelName: 'Deutz-Fahr 6095 HTS',
    brandName: 'Deutz-Fahr',
    description: 'Pour moissoneuse-batteuse',
    ref: 'moissoneuse',
    conception: 'Conventionnelle',
    engineKwPower: 260,
    engineCcPower: 240,
    maxKmhSpeed: 30,
    petrolLitreTank: 500,
    tankLitre: 8500,
    autonomyMn: null,
    liftingHeightMeter: null,
    weightKg: 11500,
    workingWidth: 7.2,
    copiesNumber: 2,
    typeId: 10,
    imageUrl: 'https://nestjsfileuploadfarmingmachine.s3.eu-west-3.amazonaws.com/New-Holland.png'
  },
  {
    modelName: 'MF Activa 7347 S',
    brandName: 'Massey Ferguson',
    description: 'Pour moissoneuse-batteuse',
    ref: 'moissoneuse',
    conception: 'Conventionnelle',
    engineKwPower: 235,
    engineCcPower: 220,
    maxKmhSpeed: 25,
    petrolLitreTank: 450,
    tankLitre: 8600,
    autonomyMn: null,
    liftingHeightMeter: null,
    weightKg: 11000,
    workingWidth: 7.6,
    copiesNumber: 3,
    typeId: 10,
    imageUrl: 'https://nestjsfileuploadfarmingmachine.s3.eu-west-3.amazonaws.com/John-Deere.png'
  },
  {
    modelName: 'Rostselmash TORUM 785',
    brandName: 'Rostselmash',
    description: 'Pour moissoneuse-batteuse',
    ref: 'moissoneuse',
    conception: 'Rotor Unique',
    engineKwPower: 390,
    engineCcPower: 370,
    maxKmhSpeed: 27,
    petrolLitreTank: 850,
    tankLitre: 12000,
    autonomyMn: null,
    liftingHeightMeter: null,
    weightKg: 17800,
    workingWidth: 9.9,
    copiesNumber: 1,
    typeId: 10,
    imageUrl: 'https://nestjsfileuploadfarmingmachine.s3.eu-west-3.amazonaws.com/John-Deere-2.png',
  },
  
];
