export const ENGINE_LIST_SPREADING  = [
  {
    modelName: 'Rollforce 6836',
    brandName: 'Rolland',
    ref: 'épandeur',
    description: 'Épandage de fumier pour grandes exploitations',
    conception: 'Système épandage horizontal à chaînes',
    engineKwPower: null,
    engineCcPower: null,
    maxKmhSpeed: null,
    petrolLitreTank: null,
    tankLitre: null,
    autonomyMn: null,
    weightKg: 8000,
    workingWidth: 24000,
    copiesNumber: 2,
    typeId: 9,
    imageUrl: ''
  },
  {
    modelName: 'Axis 40.2',
    brandName: 'Kuhn',
    ref: 'épandeur',
    description: 'Épandeur à engrais minéral',
    conception: 'Débit variable automatique',
    engineKwPower: null,
    engineCcPower: null,
    maxKmhSpeed: null,
    petrolLitreTank: null,
    tankLitre: 4000,
    autonomyMn: null,
    weightKg: null,
    workingWidth: null,
    copiesNumber: 2,
    typeId: 9,
    imageUrl: ''
  },
  {
    modelName: 'Exacta CL',
    brandName: 'Kverneland',
    ref: 'épandeur',
    description: 'Système de distribution à disques horizontaux',
    conception: '',
    engineKwPower: null,
    engineCcPower: null,
    maxKmhSpeed: null,
    petrolLitreTank: null,
    tankLitre: 4000,
    autonomyMn: null,
    weightKg: null,
    workingWidth: 36,
    copiesNumber: 2,
    typeId: 9,
    imageUrl: ''
  },
  {
    modelName: 'Allrounder',
    brandName: 'Köckerling',
    ref: 'enfouisseur',
    description: 'Enfouisseur à disques',
    conception: 'Attelage trois points',
    engineKwPower: null,
    engineCcPower: null,
    maxKmhSpeed: null,
    petrolLitreTank: null,
    tankLitre: null,
    autonomyMn: null,
    weightKg: 7200,
    workingWidth: 6,
    copiesNumber: 2,
    typeId: 9,
    imageUrl: ''
  },
  {
    modelName: 'Terrano FM',
    brandName: 'Horsch',
    ref: 'enfouisseur',
    description: 'Cultivateur-enfouisseur',
    conception: ' suspension indépendante',
    engineKwPower: null,
    engineCcPower: null,
    maxKmhSpeed: null,
    petrolLitreTank: null,
    tankLitre: null,
    autonomyMn: null,
    weightKg: null,
    workingWidth: 8,
    copiesNumber: 2,
    typeId: 9,
    imageUrl: ''
  },
];
