export const ENGINE_LIST_VARIOUS_EQUIPMENT = [
  {
    modelName: 'DJI Agras T30',
    brandName: 'DJI',
    ref: 'drone',
    description: 'Pulvérisation de pesticides et fertilisants',
    conception: 'Multicoptère-8 hélices',
    engineKwPower: null,
    engineCcPower: null,
    maxKmhSpeed: null,
    petrolLitreTank: null,
    tankLitre: 30,
    autonomyMn: 20,
    weightKg: 107,
    workingWidth: null,
    copiesNumber: 2,
    typeId: 9,
    imageUrl: 'https://nestjsfileuploadfarmingmachine.s3.eu-west-3.amazonaws.com/drone.png'
  },
  {
    modelName: 'P40',
    brandName: 'XAG',
    ref: 'drone',
    description: 'Pulvérisation, cartographie',
    conception: 'Multicoptère-8 hélices',
    engineKwPower: null,
    engineCcPower: null,
    maxKmhSpeed: null,
    petrolLitreTank: null,
    tankLitre: 40,
    autonomyMn: 25,
    weightKg: 81,
    workingWidth: null,
    copiesNumber: 2,
    typeId: 9,
    imageUrl: 'https://nestjsfileuploadfarmingmachine.s3.eu-west-3.amazonaws.com/drone.png'
  },
  {
    modelName: 'TRX420 Fourtrax Rancher',
    brandName: 'Honda',
    ref: 'quad',
    description: 'Transport de matériel, travaux agricoles légers',
    conception: 'Manuelle avec réducteur',
    engineKwPower: null,
    engineCcPower: 420,
    maxKmhSpeed: null,
    petrolLitreTank: null,
    tankLitre: null,
    autonomyMn: 20,
    weightKg: 291,
    workingWidth: null,
    copiesNumber: 2,
    typeId: 9,
    imageUrl: 'https://nestjsfileuploadfarmingmachine.s3.eu-west-3.amazonaws.com/quad.png'
  },
  {
    modelName: 'Sportsman 570 EPS',
    brandName: 'Polaris',
    ref: 'quad',
    description: 'Travaux agricoles, transport de charges lourdes',
    conception: 'Automatique CVT',
    engineKwPower: null,
    engineCcPower: 567,
    maxKmhSpeed: null,
    petrolLitreTank: null,
    tankLitre: null,
    autonomyMn: null,
    weightKg: 385,
    workingWidth: null,
    copiesNumber: 2,
    typeId: 9,
    imageUrl: 'https://nestjsfileuploadfarmingmachine.s3.eu-west-3.amazonaws.com/quad.png'
  },
  {
    modelName: 'CFX-750',
    brandName: 'Trimble',
    ref: 'gps',
    description: 'Système de guidage par GPS haute précision',
    conception: 'Real Time Kinematic',
    engineKwPower: null,
    engineCcPower: null,
    maxKmhSpeed: null,
    petrolLitreTank: null,
    tankLitre: null,
    autonomyMn: null,
    weightKg: null,
    workingWidth: null,
    copiesNumber: 2,
    typeId: 9,
    imageUrl: ''
  },
  {
    modelName: 'StarFire 3000',
    brandName: 'John Deere ',
    ref: 'gps',
    description: 'Agriculture de précision, optimisation des trajets',
    conception: 'Compatibilité avec le système ISOBUS John Deere',
    engineKwPower: null,
    engineCcPower: null,
    maxKmhSpeed: null,
    petrolLitreTank: null,
    tankLitre: null,
    autonomyMn: null,
    weightKg: null,
    workingWidth: null,
    copiesNumber: 2,
    typeId: 9,
    imageUrl: ''
  },
];
