export const ENGINE_LIST_HANDLING  = [
  {
    modelName: '',
    brandName: '',
    ref: '',
    description: '',
    conception: '',
    engineKwPower: null,
    engineCcPower: null,
    maxKmhSpeed: null,
    petrolLitreTank: null,
    tankLitre: null,
    autonomyMn: null,
    weightKg: null,
    workingWidth: null,
    copiesNumber: 2,
    typeId: 9,
    imageUrl: ''
  },
  {
    modelName: 'MLT 737-130 PS+',
    brandName: 'Manitou',
    ref: 'chargeur frontal',
    description: '',
    conception: 'Télescopique agricole',
    engineKwPower: null,
    engineCcPower: 130,
    maxKmhSpeed: null,
    petrolLitreTank: null,
    tankLitre: null,
    autonomyMn: null,
    weightKg: 11500,
    workingWidth: null,
    copiesNumber: 2,
    typeId: 9,
    imageUrl: ''
  },
  {
    modelName: '536-70 Agri Super',
    brandName: 'JCB',
    ref: 'chargeur frontal',
    description: 'Manipulation de matériaux',
    conception: 'Système hydraulique à détection de charge',
    engineKwPower: null,
    engineCcPower: 145,
    maxKmhSpeed: null,
    petrolLitreTank: null,
    tankLitre: null,
    autonomyMn: null,
    weightKg: 10800,
    workingWidth: null,
    copiesNumber: 2,
    typeId: 9,
    imageUrl: ''
  },
  {
    modelName: 'MI 25 C',
    brandName: 'Manitou',
    ref: 'lève palette',
    description: 'Chariot élévateur industriel/agricole',
    conception: 'Diesel Transmission hydrostatique',
    engineKwPower: null,
    engineCcPower: null,
    maxKmhSpeed: null,
    petrolLitreTank: null,
    tankLitre: null,
    autonomyMn: null,
    weightKg: 4200,
    workingWidth: null,
    copiesNumber: 2,
    typeId: 9,
    imageUrl: ''
  },
  {
    modelName: 'Tonero 8FG25',
    brandName: 'Toyota',
    ref: 'lève palette',
    description: 'Chariot élévateur thermique',
    conception: 'Essence/GPL',
    engineKwPower: null,
    engineCcPower: null,
    maxKmhSpeed: null,
    petrolLitreTank: null,
    tankLitre: null,
    autonomyMn: null,
    weightKg: 3900,
    workingWidth: null,
    copiesNumber: 2,
    typeId: 9,
    imageUrl: ''
  },
];
