export const ENGINE_LIST_SPECIALIZED_CULTURE  = [
  {
    modelName: '',
    brandName: '',
    ref: '',
    description: '',
    conception: '',
    engineKwPower: null,
    engineCcPower: null,
    maxKmhSpeed: null,
    petrolLitreTank: null,
    tankLitre: null,
    autonomyMn: null,
    weightKg: null,
    workingWidth: null,
    copiesNumber: 2,
    typeId: 9,
    imageUrl: ''
  },
  {
    modelName: 'Euromaus 5',
    brandName: 'ROPA',
    ref: 'arracheuse de betteraves',
    description: 'Arracheuse-chargeuse de betteraves autopropulsée',
    conception: 'rotor e-tech',
    engineKwPower: null,
    engineCcPower: 530,
    maxKmhSpeed: null,
    petrolLitreTank: null,
    tankLitre: null,
    autonomyMn: null,
    weightKg: 32000,
    workingWidth: null,
    copiesNumber: 2,
    typeId: 9,
    imageUrl: ''
  },
  {
    modelName: 'Rootster 604',
    brandName: 'Grimme',
    ref: 'arracheuse de betteraves',
    description: 'Arracheuse-chargeuse traînée',
    conception: 'centrifuge à contre-rouleaux',
    engineKwPower: null,
    engineCcPower: 300,
    maxKmhSpeed: null,
    petrolLitreTank: null,
    tankLitre: null,
    autonomyMn: null,
    weightKg: 20000,
    workingWidth: null,
    copiesNumber: 2,
    typeId: 9,
    imageUrl: ''
  },
];
