export const ENGINE_TYPE = [
  {name: 'Broyeuses', description: 'Pour broyer'},
  {name: 'Epareuses', description: 'Pour éparer'},
  {name: 'Andaineurs', description: 'Pour andainer'},
  {name: 'Arracheuses', description: 'POur arracher'},
  {name: 'Balayeuses', description: 'Pour balayer'},
  {name: 'Bétaillères', description: 'Pour bétailler'},
  {name: 'Ceuilleurs', description: 'Pour ceuillir'},
  {name: 'Chargeuses ', description: 'Pour charger'},
  {name: 'Cultivateurs', description: 'Pour cultiver'},
  {name: 'Cuves', description: 'Pour cuver'},
  {name: 'Dérouleuses', description: 'Pour dérouler'},
  {name: 'Désileuses', description: 'Pour désiler'},
  {name: 'Drones', description: 'Pour droner'},
  {name: 'Ecimeuses', description: 'Pour ecimer'},
  {name: 'Encemeuses', description: 'Pour encemer'},
  {name: 'Enfouisseurs', description: 'Pour enfouisser'},
  {name: 'Enrouleurs', description: 'Pour enrouler'},
  {name: 'Enrubanneuses', description: 'Pour enrubanner'},
  {name: 'Ensileuses' , description: 'Pour ensiler'},
  {name: 'Epandeurs', description: 'POur épander'},
  {name: 'Faneuses', description: 'Pour faner'},
  {name: 'Faucheurs', description: 'Pour faucher'},
  {name: 'Guidages', description: 'Pour guider'},
  {name: 'Herses', description: 'Pour herser'},
  {name: 'Lames de déneigement', description: 'Pour déneiger'},
  {name: 'Lèves palette', description: 'Pour lever'},
  {name: 'Moissoneuses', description: 'Pour moissonner'},
  {name: 'Nacelles', description: 'Pour naceller'},
  {name: 'Pailleuses', description: 'Pour pailler'},
  {name: 'Planteuses', description: 'Pour planter'},
  {name: 'Plateau', description: 'Pour platoifier'},
  {name: 'Pompes', description: 'Pour irriguer'},
  {name: 'Presses', description: 'Pour presser'},
  {name: 'Pulvérisateurs', description: 'Pour pulvériser'},
  {name: 'Quads', description: 'Pour quader'},
  {name: 'Remorques', description:  'Pour remorquer'},
  {name: 'Semoirs', description: 'Pour semer'},
  {name: 'Tank a lait', description: 'Pour tanker'},
  {name: 'Tracteurs', description: 'POur tracter'},
  {name: 'Sarcleuses', description: 'POur sarcler'},
];
