export const ENGINE_LIST = [
  {
    modelName: 'Axial-flow 4000',
    brandName: 'Case IH',
    conception: 'Cylindre Axial',
    engineKwPower: 210,
    engineCcPower: 180,
    MaxKmhSpeed: 30,
    PetrolLitreTank: 500,
    TankLitre: 600,
    WeightKg: 6000,
    WorkingWidth: 14,
    CopiesNumber: 2,
  },
  {
    modelName: 'Lexion 8900',
    brandName: 'Claas',
    conception: 'Hybride',
    engineKwPower: 485,
    engineCcPower: 460,
    MaxKmhSpeed: 40,
    PetrolLitreTank: 1150,
    TankLitre: 18000,
    WeightKg: 18700,
    WorkingWidth: 13.8,
    CopiesNumber: 1,
  },
  {
    modelName: 'S790',
    brandName: 'John Deere',
    conception: 'Conventionnelle',
    engineKwPower: 460,
    engineCcPower: 435,
    MaxKmhSpeed: 40,
    PetrolLitreTank: 1250,
    TankLitre: 14100,
    WeightKg: 19000,
    WorkingWidth: 12.2,
    CopiesNumber: 2,
  },
  {
    modelName: 'Ideal 9T',
    brandName: 'Fendt',
    conception: 'Rotor Unique',
    engineKwPower: 483,
    engineCcPower: 455,
    MaxKmhSpeed: 40,
    PetrolLitreTank: 1500,
    TankLitre: 17100,
    WeightKg: 21000,
    WorkingWidth: 12.2,
    CopiesNumber: 1,
  },
  {
    modelName: 'CR10.90',
    brandName: 'New Holland',
    conception: 'Twin Rotor',
    engineKwPower: 515,
    engineCcPower: 490,
    MaxKmhSpeed: 30,
    PetrolLitreTank: 1300,
    TankLitre: 14500,
    WeightKg: 24500,
    WorkingWidth: 13.7,
    CopiesNumber: 1,
  },
  {
    modelName: 'Trion 750',
    brandName: 'Claas',
    conception: 'Hybride',
    engineKwPower: 320,
    engineCcPower: 300,
    MaxKmhSpeed: 30,
    PetrolLitreTank: 800,
    TankLitre: 12000,
    WeightKg: 15000,
    WorkingWidth: 9.3,
    CopiesNumber: 3,
  },
  {
    modelName: 'Tucano 580',
    brandName: 'Claas',
    conception: 'Conventionnelle',
    engineKwPower: 280,
    engineCcPower: 260,
    MaxKmhSpeed: 25,
    PetrolLitreTank: 650,
    TankLitre: 10000,
    WeightKg: 13500,
    WorkingWidth: 7.7,
    CopiesNumber: 2,
  },
  {
    modelName: 'TC5.90',
    brandName: 'New Holland',
    conception: 'Conventionnelle',
    engineKwPower: 220,
    engineCcPower: 200,
    MaxKmhSpeed: 30,
    PetrolLitreTank: 400,
    TankLitre: 6400,
    WeightKg: 10500,
    WorkingWidth: 6.1,
    CopiesNumber: 4,
  },
  {
    modelName: 'Deutz-Fahr 6095 HTS',
    brandName: 'Deutz-Fahr',
    conception: 'Conventionnelle',
    engineKwPower: 260,
    engineCcPower: 240,
    MaxKmhSpeed: 30,
    PetrolLitreTank: 500,
    TankLitre: 8500,
    WeightKg: 11500,
    WorkingWidth: 7.2,
    CopiesNumber: 2,
  },
  {
    modelName: 'MF Activa 7347 S',
    brandName: 'Massey Ferguson',
    conception: 'Conventionnelle',
    engineKwPower: 235,
    engineCcPower: 220,
    MaxKmhSpeed: 25,
    PetrolLitreTank: 450,
    TankLitre: 8600,
    WeightKg: 11000,
    WorkingWidth: 7.6,
    CopiesNumber: 3,
  },
  {
    modelName: 'Rostselmash TORUM 785',
    brandName: 'Rostselmash',
    conception: 'Rotor Unique',
    engineKwPower: 390,
    engineCcPower: 370,
    MaxKmhSpeed: 27,
    PetrolLitreTank: 850,
    TankLitre: 12000,
    WeightKg: 17800,
    WorkingWidth: 9.9,
    CopiesNumber: 1,
  },
];
